version: '3.5'

services:

  # Services
  consignment:
    restart: always
    build: ./shippy-service-consignment
    depends_on:
      - datastore
      - vessel
    links:
      - datastore
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    restart: always
    build: ./shippy-service-vessel
    ports:
      - 50052:50052
    environment:
      MICRO_SERVER_ADDRESS: ":50052"
      DB_HOST: "mongodb://datastore:27017"

  user:
    restart: always
    build: ./shippy-service-user
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "postgresdb"
      DB_USER: "admin"
      DB_PASSWORD: "password"
      DB_NAME: "postgres"
    networks: 
      dev:
        aliases: 
          - usersrv

  # Commands
  cli:
    build: ./shippy-cli-consignment

  user-cli:
    build: ./shippy-cli-user
    networks: 
      - dev

  # Database tier
  datastore:
    image: mongo
    container_name: datastore
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

  database:
    image: postgres:alpine
    hostname: postgresdb
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432
    networks: 
      dev:
        aliases: 
          - postgresdb

networks:
  dev: